server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://pokoed.xyz:3306/chargerPin
    username: pokoed
    password: 20041230zen!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
